# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: haberdasher.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient
try:
	from twirp.async_client import AsyncTwirpClient
	_async_available = True
except ModuleNotFoundError:
	_async_available = False

_sym_db = _symbol_database.Default()

class HaberdasherServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/twirp.example.haberdasher.Haberdasher"
		self._endpoints = {
			"GetDollarRate": Endpoint(
				service_name="Haberdasher",
				name="GetDollarRate",
				function=getattr(service, "GetDollarRate"),
				input=_sym_db.GetSymbol("twirp.example.haberdasher.ValuteId"),
				output=_sym_db.GetSymbol("twirp.example.haberdasher.DollarRate"),
			),
		}

class HaberdasherClient(TwirpClient):

	def GetDollarRate(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/twirp.example.haberdasher.Haberdasher/GetDollarRate",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("twirp.example.haberdasher.DollarRate"),
			**kwargs,
		)


if _async_available:
	class AsyncHaberdasherClient(AsyncTwirpClient):

		async def GetDollarRate(self, *, ctx, request, server_path_prefix="/twirp", session=None, **kwargs):
			return await self._make_request(
				url=F"{server_path_prefix}/twirp.example.haberdasher.Haberdasher/GetDollarRate",
				ctx=ctx,
				request=request,
				response_obj=_sym_db.GetSymbol("twirp.example.haberdasher.DollarRate"),
				session=session,
				**kwargs,
			)
